$("#selh3").click(function(event){
	$("#contenedor").load('paginas/colombia.html');
});
$("#selh4").click(function(event){
	$("#inicio").load('index.html');
});
$("#selh5").click(function(event){
	$("#contenedor").load('paginas/contacto.html');
});
